# Site Info
title:              "Lancaster Blog"
description:        "A minimalist Jekyll theme"
author_name:        "Jim Perrello" # change this to your name
logo_url:           https://api.github.com/users/jvperrella # Get it from GitHub API: https://api.github.com/users/<username>

# Site Settings
url:                https://maxtheaxe.github.io # main url
baseurl:            /lancaster-blog
permalink:          /:title # Post permalink
timezone:           America/New_York # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            false  # enables support for mathjax - set to 'false' to disable
social_share_previews: true

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script" ]
plugins:
  - jekyll-sitemap



defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
